### ISSUE TITLE
heavy logs in browser console

### ISSUE THREAD

**Issue by mstrong-tech** [starknet-community-libs/get-starknet#155]
Hey guys!

I am using `get-starknet` module for wallet connection but I found crazy logs in the browser console.
`import { getStarknet, connect, IStarknetWindowObject } from "get-starknet"`

It seems you're logging all messages. Is it mandatory or could you address it?

![image](https://user-images.githubusercontent.com/59189994/194583297-3ee738a9-7696-45ad-a091-d13c54d9a1ef.png)

**Comment by avimak** [comment]
sorry. it's not related to `get-starknet` itself; should be fixed on wallet side soon. thanks 🙏

**Comment by avimak** [comment]
It's already addressed and deployed, just waiting for store approvals,
thanks!
